# Generated by Django 3.2.5 on 2021-07-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DemoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_username', models.CharField(max_length=200)),
                ('db_password', models.CharField(max_length=200)),
                ('db_url', models.CharField(max_length=200)),
                ('db_foo', models.CharField(max_length=200)),
            ],
        ),
    ]
