# Generated by Django 3.2.5 on 2021-07-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='democonfig',
            name='db_foo',
        ),
    ]
