# Generated by Django 3.2.5 on 2021-07-13 19:29

import csv
import logging
import os
from django.conf import settings
from django.db import migrations

logger = logging.getLogger(__name__)

def load_collection_aliases(apps, schema_editor):
    # We can't import the Collection model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Collection = apps.get_model("demo", "Collection")
    data_dir = os.path.join(settings.BASE_DIR, "demo", "data")
    load_path = os.path.abspath(os.path.join(data_dir, "collection_name_to_alias.csv"))

    with open(load_path) as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            collection = Collection.objects.create(
                name = row["collection_name"],
                alias = row["collection_alias"],
            )
            if not collection:
                raise Exception("Failed to insert row %s", row)

    logger.info("Loaded collection alias data.")
 

class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_rename_democonfig_config'),
    ]

    operations = [
        migrations.RunPython(load_collection_aliases),
    ]
